name 'fluentd'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures fluentd'
long_description 'Installs/Configures fluentd'
version '0.1.0'
