name 'rundeck'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures rundeck'
long_description 'Installs/Configures rundeck'
version '0.1.0'
