name 'terraform'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures terraform'
long_description 'Installs/Configures terraform'
version '0.1.0'
