default['consul']['install_version'] = "0.5.2"
default['consul']['uid'] = "600"
default['consul']['gid'] = "600"
default['consul']['config_dir'] = "/etc/consul"
default['consul']['data_dir'] = "/var/lib/consul"
