name 'couchbase'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures couchbase'
long_description 'Installs/Configures couchbase'
version '0.1.0'
